const PATH_NAME = {
  HOME: '/',
  AUTH: '/auth',
  NOT_FOUND: '*',
  MEMBER: '/member',
  STUDENT: '/student',
  ADMIN: '/admin',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_USERS: '/admin/users',
  ADMIN_SEASON: '/admin/season',
  HACKATHON_DETAIL_PAGE: '/admin/hackathons',
  HACKATHON_EDIT_PAGE: '/admin/hackathons/edit',
  ADMIN_CHALLENGE_MANAGE: '/admin/challenges',
  ADMIN_TEAMS: '/admin/teams',
  ADMIN_FILES: '/admin/files',
  ADMIN_SETTINGS: '/admin/settings',
  HACKATHON_CREATE_PAGE: '/admin/hackathons/create',
  ADMIN_HACKATHONS: '/admin/hackathons',
  ADMIN_HACKATHON_PHASES: '/admin/hackathons/hackathon-phases',
  ADMIN_PRIZES: '/admin/hackathons/prizes',
  STUDENT_DASHBOARD: '/student/dashboard',
  STUDENT_HACKATHONS: '/student/hackathons',
  STUDENT_TEAMS: '/student/teams',
  STUDENT_MY_TEAM: '/student/my-team',
  STUDENT_SUBMISSIONS: '/student/submissions',
  STUDENT_PROFILE: '/student/profile',
  STUDENT_LEADERBOARD: '/student/leaderboard',
  STUDENT_NOTIFICATIONS: '/student/notifications',
  USER_INFO: '/user/profile',
  ADMIN_CHALLENGES: '/admin/challenges',
  PARTNER: '/partner',
  PARTNER_HACKATHONS: '/partner/hackathons',
  PARTNER_CHALLENGES: '/partner/challenges',
  PARTNER_TEAM_SCORES: '/partner/hackathons/',
};

export { PATH_NAME };
