const PATH_NAME = {
  HOME: '/',
  AUTH: '/auth',
  NOT_FOUND: '*',
  MEMBER: '/member',
  STUDENT: '/student',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_SEASON: '/admin/season',
  ADMIN_TEAMS: '/admin/team',
  ADMIN_GROUPS: '/admin/groups',
  ADMIN_APPEALS: '/admin/appeal',
  ADMIN_HACKATHONS: '/admin/hackathons',
  ADMIN_HACKATHON_PHASES: '/admin/hackathons/hackathon-phases',
  ADMIN_PRIZES: '/admin/hackathons/prizes',
  ADMIN_RANKINGS: '/admin/hackathons/rankings',
  STUDENT_DASHBOARD: '/student/dashboard',
  STUDENT_HACKATHONS: '/student/hackathons',
  STUDENT_TEAMS: '/student/teams',
  STUDENT_MY_TEAM: '/student/my-team',
  STUDENT_PROFILE: '/student/profile',
  STUDENT_LEADERBOARD: '/student/leaderboard',
  STUDENT_NOTIFICATIONS: '/student/notifications',
  STUDENT_PHASE_DETAIL: '/student/hackathons/:hackathonId/phases/:phaseId',
  USER_INFO: '/user/profile',
  ADMIN_CHALLENGES: '/admin/challenges',
  ADMIN_TRACKS: '/admin/tracks',
  ADMIN_CRITERIAS: '/admin/criterias',
  ADMIN_FILES: '/admin/files',
  ADMIN_SETTINGS: '/admin/settings',
  PARTNER: '/partner',
  PARTNER_HACKATHONS: '/partner/hackathons',
  PARTNER_HACKATHON_PHASES: '/partner/hackathons/hackathon-phases',
  PARTNER_CHALLENGES: '/partner/challenges',
  PARTNER_TEAM_SCORES: '/partner/score',
  PARTNER_PRIZES: '/partner/prizes',
  JUDGE: '/judge',
  JUDGE_TEAM_SCORES: '/judge/score',
  JUDGE_CHALLENGES: '/judge/challenges',
  JUDGE_HACKATHON_PHASES: '/judge/score/phase',
  CHAPTER: '/chapter',
  CHAPTER_DASHBOARD: '/chapter/dashboard',
  CHAPTER_VERIFY_STUDENTS: '/chapter/verify-students',
  CHAPTER_MENTOR_MANAGEMENT: '/chapter/mentor-management',
  CHAPTER_TEAMS: '/chapter/teams',
  CHAPTER_RESULTS: '/chapter/results',
  CHAPTER_TEAM_HACKATHON_APPROVAL: '/chapter/team-hackathon-approval',
  CHAPTER_NOTIFICATIONS: '/chapter/notifications',
  MENTOR: '/mentor',
  MENTOR_DASHBOARD: '/mentor/dashboard',
  MENTOR_RESOURCES: '/mentor/resources',
  MENTOR_NOTIFICATIONS: '/mentor/notifications',
  MENTOR_PROFILE: '/mentor/profile',
  MENTOR_ASSIGNMENTS: '/mentor/assignments',
  MENTOR_GROUP_CHAT: '/mentor/group-chat',
}

const GROUP = {
  [PATH_NAME.ADMIN_HACKATHON_PHASES]: [
    PATH_NAME.ADMIN_TRACKS,
    PATH_NAME.ADMIN_CRITERIAS,
  ],
};

export { PATH_NAME, GROUP };
